### ISSUE TITLE
Add custom error message for invalid YAML

### ISSUE THREAD

**Issue by alita-moore** [ethereum/EIP-Bot#34]
https://github.com/ethereum/EIPs/pull/4512#issuecomment-983230624

**Comment by alita-moore** [comment]
just or reference, this is a feature requested by myself and it's low priority

**Comment by Pandapip1** [comment]
@alita-moore could you elaborate since you're no longer actively maintaining this?

**Comment by alita-moore** [comment]
> @alita-moore could you elaborate since you're no longer actively maintaining this?

It's just to add a better error for the linked error

**Comment by JEAlfonsoP** [comment]
I believe this is the error example:

A critical exception has occurred (cc @alita-moore):
Message: can not read a block mapping entry; a multiline key may not be an implicit key at line 3, column 7:
author: kkimos [bol@zju.edu.cn](mailto:bol@zju.edu.cn)
^

Pandapip1: Has you seen this error again lately ?
I think EIPW fixs this kind of string miss-formatting? (question)

**Comment by Pandapip1** [comment]
I have seen it once. I can't remember where.

**Comment by JEAlfonsoP** [comment]
I will take a look on it, but the "bug" was wrong or poor  error messaging for author's ID (wrong github and/or email formatting) in the EIP header. 
I will review the EIP-Bot and EIPW code but I think this has been solved with EIPW.

**Comment by Pandapip1** [comment]
This has not been solved with eipw. This is an EIP-Bot bug.

**Comment by JEAlfonsoP** [comment]
Do you have any particular idea about the writing for this error message: ??

**Comment by JEAlfonsoP** [comment]
@Pandapip1   ^

**Comment by SamWilsn** [comment]
I'm not looking at this one.

**Comment by JEAlfonsoP** [comment]
I have reviewed all assertion and require files corresponding to this kind of error (bad formatting in the EIP header - specifically authors) and looks like the error message was properly edited also the editing time of the EIP-Bot repo vs the time the error was commented suggests it was probably fixed. 
I will try to create a test case for it and will get back either suggesting to close this issue or with a PR about it.

**Comment by JEAlfonsoP** [comment]
Hi, I performed a test case for this error, this is the report:
This error is thrown by Auto Label Bot.
https://github.com/JEAlfonsoP/EIPs/actions/runs/3071036422/jobs/4961365805

YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 3, column 7:
    author: kimos puncrab@outlook.com
          ^
    at generateError (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:[10](https://github.com/JEAlfonsoP/EIPs/actions/runs/3071036422/jobs/4961365805#step:2:11)296:14)
    at throwError (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:10302:13)
    at readBlockMapping (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:10904:13)
    at composeNode (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:[11](https://github.com/JEAlfonsoP/EIPs/actions/runs/3071036422/jobs/4961365805#step:2:12)102:82)
    at readDocument (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:1[12](https://github.com/JEAlfonsoP/EIPs/actions/runs/3071036422/jobs/4961365805#step:2:13)20:7)
    at loadDocuments (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:11262:9)
    at load (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:11280:23)
    at safeLoad (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:11296:[14](https://github.com/JEAlfonsoP/EIPs/actions/runs/3071036422/jobs/4961365805#step:2:15))
    at parse2 (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:11956:24)
    at extractor (/home/runner/work/_actions/Pandapip1/jekyll-label-action/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js:11923:[16](https://github.com/JEAlfonsoP/EIPs/actions/runs/3071036422/jobs/4961365805#step:2:17))

I do not see any problem with this, since there is an error. If you want to change the message in :
https://github.com/Pandapip1/jekyll-label-action/blob/28a89dbbef321fceaf3cff17f4d29c7a033c3d56/dist/index.js
Line 10904: throwError(state, "can not read a block mapping entry; a multiline key may not be an implicit key");
for another message is up to Editors.

Please let me know if you need something else in order to close this issue. So I can move forward for the next one. Ty.

**Comment by Pandapip1** [comment]
Ah - I suggest perhaps the following error:

`The preamble is invalid. Please double check the syntax.`

**Comment by JEAlfonsoP** [comment]
PR:

https://github.com/Pandapip1/jekyll-label-action/pull/87
